export const staticRoutes: Models.RouteItem[] = [
  {
    "name": "dashboard",
    "path": "/dashboard",
    "title": "Dashboard",
    "require": true,
    "access": true,
    "icon": "icon-park-outline:analysis",
    "tab": true,
    "type": "dir",
    "component": null,
    "pid": null,
    "id": 1
  },
  {
    "name": "workbench",
    "path": "/dashboard/workbench",
    "title": "Workbench",
    "require": true,
    "access": true,
    "icon": "icon-park-outline:alarm",
    "tab": true,
    "pin": true,
    "type": "page",
    "component": "/dashboard/workbench/index.vue",
    "pid": 1,
    "id": 2
  },
  {
    "name": "monitor",
    "path": "/dashboard/monitor",
    "title": "Monitoring Page",
    "require": true,
    "access": true,
    "icon": "icon-park-outline:anchor",
    "tab": true,
    "type": "page",
    "component": "/dashboard/monitor/index.vue",
    "pid": 1,
    "id": 3
  },
  {
    "name": "profile",
    "path": "/profile",
    "title": "Personal Center",
    "require": true,
    "access": true,
    "hide": true,
    "icon": "carbon:user-avatar-filled-alt",
    "tab": true,
    "component": "/system/profile/index.vue",
    "pid": null,
    "id": 4
  },
  {
    "name": "billing",
    "path": "/billing",
    "title": "Billing",
    "require": true,
    "icon": "icon-park-outline:transaction-order",
    "tab": true,
    "type": "dir",
    "component": null,
    "pid": null,
    "id": 53
  },
  {
    "name": "billingList",
    "path": "/billing/list",
    "title": "Billing list",
    "group": "billing",
    "require": true,
    "icon": "icon-park-outline:bill",
    "tab": true,
    "component": "/manage/billing/index.vue",
    "pid": 53,
    "id": 54
  },
  {
    "name": "billingReport",
    "path": "/billing/report",
    "title": "Billing report",
    "group": "billing",
    "require": true,
    "icon": "icon-park-outline:bill",
    "tab": true,
    "component": "/manage/billing/Report.vue",
    "pid": 53,
    "id": 58
  },
  {
    "name": "billingItems",
    "path": "/billing/items",
    "title": "Billing items",
    "group": "billing-items",
    "require": true,
    "icon": "icon-park-outline:menu-fold-one",
    "tab": true,
    "component": "/manage/billing-items/index.vue",
    "pid": 53,
    "id": 55
  },
  {
    "name": "billingItemsGroups",
    "path": "/billing/items-groups",
    "title": "Billing items groups",
    "group": "billing-items",
    "require": true,
    "icon": "icon-park-outline:baby-mobile",
    "tab": true,
    "component": "/system/groups/index.vue",
    "pid": 53,
    "id": 56
  },
  {
    "name": "billingGroups",
    "path": "/billing/groups",
    "title": "Billing Groups",
    "group": "billing",
    "require": true,
    "icon": "icon-park-outline:group",
    "tab": true,
    "component": "/system/groups/index.vue",
    "pid": 53,
    "id": 57
  },
  {
    "name": "content",
    "path": "/content",
    "title": "Content",
    "require": true,
    "icon": "icon-park-outline:browser",
    "tab": true,
    "type": "dir",
    "component": null,
    "pid": null,
    "id": 47
  },
  // {
  //   "name": "post",
  //   "path": "post",
  //   "title": "post",
  //   "require": true,
  //   "icon": "icon-park-outline:view-grid-detail",
  //   "tab": true,
  //   "type": "dir",
  //   "component": null,
  //   "pid": null,
  //   "id": 50
  // },
  {
    "name": "page",
    "path": "/page",
    "redirect": "/page/list",
    "title": "Page",
    "group": "page",
    "require": true,
    "icon": "icon-park-outline:page",
    "tab": true,
    "component": null,
    "pid": 47,
    "id": 100
  },
  {
    "name": "pageList",
    "path": "/page/list",
    "title": "Page List",
    "group": "page",
    "require": true,
    "icon": "icon-park-outline:list-view",
    "tab": true,
    "hide": true,
    "component": "/manage/page/index.vue",
    "pid": 100,
    "id": 101
  },
  {
    "name": "pageAdd",
    "path": "/page/add",
    "title": "Page Add",
    "group": "page",
    "require": true,
    "icon": "icon-park-outline:list-add",
    "tab": true,
    "hide": true,
    "component": "/manage/page/add.vue",
    "pid": 100,
    "id": 102
  },
  {
    "name": "pageEdit",
    "path": "/page/edit/:id",
    "title": "Page Edit",
    "group": "page",
    "require": true,
    "icon": "icon-park-outline:edit-one",
    "tab": true,
    "hide": true,
    "component": "/manage/page/add.vue",
    "pid": 100,
    "id": 103
  },
  {
    "name": "post",
    "path": "/post",
    "redirect": "/post/list",
    "title": "Post",
    "group": "post",
    "require": true,
    "icon": "icon-park-outline:view-grid-list",
    "tab": true,
    "component": null,
    "pid": 47,
    "id": 200
  },
  {
    "name": "postList",
    "path": "/post/list",
    "title": "Post List",
    "group": "post",
    "require": true,
    "icon": "icon-park-outline:list-view",
    "tab": true,
    "hide": true,
    "component": "/manage/post/index.vue",
    "pid": 200,
    "id": 201
  },
  {
    "name": "postAdd",
    "path": "/post/add",
    "title": "Post Add",
    "group": "post",
    "require": true,
    "icon": "icon-park-outline:list-add",
    "tab": true,
    "hide": true,
    "component": "/manage/post/add.vue",
    "pid": 200,
    "id": 202
  },
  {
    "name": "postEdit",
    "path": "/post/edit/:id",
    "title": "Post Edit",
    "group": "post",
    "require": true,
    "icon": "icon-park-outline:edit-one",
    "tab": true,
    "hide": true,
    "component": "/manage/post/add.vue",
    "pid": 200,
    "id": 203
  },
  {
    "name": "postGroups",
    "path": "/post-groups",
    "title": "Post Groups",
    "group": "post",
    "require": true,
    "icon": "icon-park-outline:layout-five",
    "tab": true,
    "component": "/system/groups/index.vue",
    "pid": 47,
    "id": 300
  },
  // {
  //   "name": "postGroups",
  //   "path": "/post-groups",
  //   "redirect": "/post-groups/list",
  //   "title": "Post Groups",
  //   "group": "post",
  //   "require": true,
  //   "icon": "icon-park-outline:layout-five",
  //   "tab": true,
  //   "component": null,
  //   "pid": 47,
  //   "id": 300
  // },
  // {
  //   "name": "postGroupsList",
  //   "path": "/post-groups/list",
  //   "title": "Post Groups List",
  //   "group": "post",
  //   "require": true,
  //   "icon": "icon-park-outline:list-view",
  //   "tab": true,
  //   "hide": true,
  //   "component": "/manage/post-groups/list.vue",
  //   "pid": 300,
  //   "id": 301
  // },
  // {
  //   "name": "postGroupsAdd",
  //   "path": "/post-groups/add",
  //   "title": "Post Groups Add",
  //   "group": "post",
  //   "require": true,
  //   "icon": "icon-park-outline:list-add",
  //   "tab": true,
  //   "hide": true,
  //   "component": "/manage/post-groups/add.vue",
  //   "pid": 300,
  //   "id": 302
  // },
  // {
  //   "name": "postGroupsEdit",
  //   "path": "/post-groups/edit/:id",
  //   "title": "Post Groups Edit",
  //   "group": "post",
  //   "require": true,
  //   "icon": "icon-park-outline:edit-one",
  //   "tab": true,
  //   "hide": true,
  //   "component": "/manage/post-groups/add.vue",
  //   "pid": 300,
  //   "id": 303
  // },
  {
    "name": "product",
    "path": "/product/list",
    "title": "List",
    "group": "product",
    "require": true,
    "icon": "icon-park-outline:layers",
    "tab": true,
    "component": "/manage/product/index.vue",
    "pid": 47,
    "id": 400
  },
  {
    "name": "productGroups",
    "path": "/product/groups",
    "title": "Product Groups",
    "group": "product",
    "require": true,
    "icon": "icon-park-outline:vertical-tidy-up",
    "tab": true,
    "component": "/system/groups/index.vue",
    "pid": 47,
    "id": 500
  },
  {
    "name": "menu",
    "path": "/menu",
    "title": "Menu",
    "require": true,
    "icon": "icon-park-outline:application-menu",
    "tab": true,
    "component": "/manage/menu/index.vue",
    "pid": 47,
    "id": 600
  },
  // {
  //   "name": "slider",
  //   "path": "/slider",
  //   "title": "Slider",
  //   "require": true,
  //   "icon": "icon-park-outline:slide-two",
  //   "tab": true,
  //   "component": "/manage/slider/index.vue",
  //   "pid": 47,
  //   "id": 601
  // },
  {
    "name": "company",
    "path": "/company",
    "title": "Company",
    "require": true,
    "icon": "icon-park-outline:green-house",
    "tab": true,
    "component": "/manage/company/index.vue",
    "pid": 47,
    "id": 602
  },
  {
    "name": "system",
    "path": "/system",
    "title": "System",
    "require": true,
    "icon": "icon-park-outline:system",
    "tab": true,
    "type": "dir",
    "component": null,
    "pid": null,
    "id": 5
  },
  {
    "name": "users",
    "path": "/system/users",
    "title": "User",
    "group": "user",
    "require": true,
    "icon": "icon-park-outline:every-user",
    "tab": true,
    "component": "/system/users/index.vue",
    "pid": 5,
    "id": 6
  },
  {
    "name": "roles",
    "path": "/system/roles",
    "title": "Roles",
    "require": true,
    "icon": "icon-park-outline:people-safe",
    "tab": true,
    "component": "/system/roles/index.vue",
    "pid": 5,
    "id": 7
  },
  {
    "name": "routes",
    "path": "/system/routes",
    "title": "Route",
    "require": true,
    "icon": "icon-park-outline:application-menu",
    "tab": true,
    "component": "/system/routes/index.vue",
    "pid": 5,
    "id": 8
  },
  {
    "name": "userGroups",
    "path": "/system/groups-user",
    "title": "User groups",
    "group": "user",
    "require": true,
    "icon": "icon-park-outline:tree-list",
    "tab": true,
    "component": "/system/groups/index.vue",
    "pid": 5,
    "id": 45
  },
  {
    "name": "options",
    "path": "/system/options",
    "title": "Options",
    "require": true,
    "icon": "icon-park-outline:connection-box",
    "tab": true,
    "component": "/system/options/index.vue",
    "pid": 5,
    "id": 46
  },
  {
    "name": "config",
    "path": "/system/config",
    "title": "Config",
    "require": true,
    "icon": "icon-park-outline:config",
    "tab": true,
    "component": "/system/config/index.vue",
    "pid": 5,
    "id": 60
  },
  // {
  //   "name": "tools",
  //   "path": "/tools",
  //   "title": "Tools",
  //   "require": true,
  //   "icon": "icon-park-outline:toolkit",
  //   "tab": true,
  //   "type": "dir",
  //   "component": null,
  //   "pid": null,
  //   "id": 10
  // },
  // {
  //   "name": "video",
  //   "path": "/tools/video",
  //   "title": "Video",
  //   "require": true,
  //   "icon": "icon-park-outline:carousel-video",
  //   "tab": true,
  //   "type": "page",
  //   "component": "/tools/video/index.vue",
  //   "pid": 10,
  //   "id": 11
  // },
  // {
  //   "name": "youtube",
  //   "path": "/tools/youtube",
  //   "title": "Youtube",
  //   "require": true,
  //   "icon": "icon-park-outline:youtube",
  //   "tab": true,
  //   "type": "page",
  //   "component": "/tools/youtube/index.vue",
  //   "pid": 10,
  //   "id": 12
  // },
  // {
  //   "name": "menu",
  //   "path": "/system/menu",
  //   "title": "Menu",
  //   "require": true,
  //   "icon": "icon-park-outline:application-menu",
  //   "tab": true,
  //   "component": "/system/menu/index.vue",
  //   "pid": 5,
  //   "id": 9
  // },
  {
    "name": "demo",
    "path": "/demo",
    "title": "Function Example",
    "require": true,
    "icon": "icon-park-outline:application-one",
    "tab": true,
    "type": "dir",
    "component": null,
    "pid": null,
    "id": 13
  },
  // {
  //   "name": "multi",
  //   "path": "/demo/multi",
  //   "title": "Multi-level menu demonstration",
  //   "require": true,
  //   "icon": "icon-park-outline:list",
  //   "tab": true,
  //   "type": "dir",
  //   "component": null,
  //   "pid": 13,
  //   "id": 14
  // },
  // {
  //   "name": "multi2",
  //   "path": "/demo/multi/multi2",
  //   "title": "Multi-level menu subpage",
  //   "require": true,
  //   "icon": "icon-park-outline:list",
  //   "tab": true,
  //   "type": "page",
  //   "component": "/demo/multi/multi2/index.vue",
  //   "pid": 14,
  //   "id": 15
  // },
  // {
  //   "name": "multi2Detail",
  //   "path": "/demo/multi/multi2/detail",
  //   "title": "Menu details page",
  //   "require": true,
  //   "icon": "icon-park-outline:list",
  //   "tab": true,
  //   "hide": true,
  //   "active": "/multi/multi2",
  //   "type": "page",
  //   "component": "/demo/multi/multi2/detail/index.vue",
  //   "pid": 14,
  //   "id": 16
  // },
  // {
  //   "name": "multi3",
  //   "path": "/demo/multi/multi3",
  //   "title": "Multi-level menu",
  //   "require": true,
  //   "icon": "icon-park-outline:list",
  //   "tab": true,
  //   "type": "dir",
  //   "component": null,
  //   "pid": 14,
  //   "id": 17
  // },
  // {
  //   "name": "multi4",
  //   "path": "/demo/multi/multi3/multi4",
  //   "title": "Multi-level menu 3-1",
  //   "require": true,
  //   "icon": "icon-park-outline:list",
  //   "tab": true,
  //   "component": "/demo/multi/multi3/multi4/index.vue",
  //   "pid": 17,
  //   "id": 18
  // },
  // {
  //   "name": "list",
  //   "path": "/demo/list",
  //   "title": "List page",
  //   "require": true,
  //   "icon": "icon-park-outline:list-two",
  //   "tab": true,
  //   "type": "dir",
  //   "component": null,
  //   "pid": 13,
  //   "id": 19
  // },
  // {
  //   "name": "commonList",
  //   "path": "/demo/list/commonList",
  //   "title": "Commonly used list",
  //   "require": true,
  //   "icon": "icon-park-outline:list-view",
  //   "tab": true,
  //   "component": "/demo/list/commonList/index.vue",
  //   "pid": 19,
  //   "id": 20
  // },
  // {
  //   "name": "cardList",
  //   "path": "/demo/list/cardList",
  //   "title": "Card List",
  //   "require": true,
  //   "icon": "icon-park-outline:view-grid-list",
  //   "tab": true,
  //   "component": "/demo/list/cardList/index.vue",
  //   "pid": 19,
  //   "id": 21
  // },
  // {
  //   "name": "draggableList",
  //   "path": "/demo/list/draggableList",
  //   "title": "Drag-and-drop list",
  //   "require": true,
  //   "icon": "icon-park-outline:menu-fold",
  //   "tab": true,
  //   "component": "/demo/list/draggableList/index.vue",
  //   "pid": 19,
  //   "id": 22
  // },
  // {
  //   "name": "fetch",
  //   "path": "/demo/fetch",
  //   "title": "Request Example",
  //   "require": true,
  //   "icon": "icon-park-outline:international",
  //   "tab": true,
  //   "component": "/demo/fetch/index.vue",
  //   "pid": 13,
  //   "id": 23
  // },
  // {
  //   "name": "echarts",
  //   "path": "/demo/echarts",
  //   "title": "ECharts",
  //   "require": true,
  //   "icon": "icon-park-outline:chart-proportion",
  //   "tab": true,
  //   "component": "/demo/echarts/index.vue",
  //   "pid": 13,
  //   "id": 24
  // },
  // {
  //   "name": "map",
  //   "path": "/demo/map",
  //   "title": "Map",
  //   "require": true,
  //   "icon": "carbon:map",
  //   "tab": true,
  //   "keep": true,
  //   "component": "/demo/map/index.vue",
  //   "pid": 13,
  //   "id": 25
  // },
  // {
  //   "name": "editor",
  //   "path": "/demo/editor",
  //   "title": "Editor",
  //   "require": true,
  //   "icon": "icon-park-outline:editor",
  //   "tab": true,
  //   "type": "dir",
  //   "component": null,
  //   "pid": 13,
  //   "id": 26
  // },
  // {
  //   "name": "editorMd",
  //   "path": "/demo/editor/md",
  //   "title": "MarkDown",
  //   "require": true,
  //   "icon": "ri:markdown-line",
  //   "tab": true,
  //   "component": "/demo/editor/md/index.vue",
  //   "pid": 26,
  //   "id": 27
  // },
  // // {
  // //   "name": "editorRich",
  // //   "path": "/demo/editor/rich",
  // //   "title": "Rich text",
  // //   "require": true,
  // //   "icon": "icon-park-outline:edit-one",
  // //   "tab": true,
  // //   "component": "/demo/editor/rich/index.vue",
  // //   "pid": 26,
  // //   "id": 28
  // // },
  // {
  //   "name": "clipboard",
  //   "path": "/demo/clipboard",
  //   "title": "Clipboard",
  //   "require": true,
  //   "icon": "icon-park-outline:clipboard",
  //   "tab": true,
  //   "component": "/demo/clipboard/index.vue",
  //   "pid": 13,
  //   "id": 29
  // },
  {
    "name": "icons",
    "path": "/demo/icons",
    "title": "icon",
    "require": true,
    "icon": "local:cool",
    "tab": true,
    "component": "/demo/icons/index.vue",
    "pid": 13,
    "id": 30
  },
  // {
  //   "name": "QRCode",
  //   "path": "/demo/QRCode",
  //   "title": "QR code",
  //   "require": true,
  //   "icon": "icon-park-outline:two-dimensional-code",
  //   "tab": true,
  //   "component": "/demo/QRCode/index.vue",
  //   "pid": 13,
  //   "id": 31
  // },
  // {
  //   "name": "documents",
  //   "path": "/demo/documents",
  //   "title": "External link document",
  //   "require": true,
  //   "icon": "icon-park-outline:file-doc",
  //   "tab": true,
  //   "type": "dir",
  //   "component": null,
  //   "pid": 13,
  //   "id": 32
  // },
  // {
  //   "name": "documentsVue",
  //   "path": "/demo/documents/vue",
  //   "title": "Vue",
  //   "require": true,
  //   "icon": "logos:vue",
  //   "tab": true,
  //   "component": "/demo/documents/vue/index.vue",
  //   "pid": 32,
  //   "id": 33
  // },
  // {
  //   "name": "documentsVite",
  //   "path": "/demo/documents/vite",
  //   "title": "Vite",
  //   "require": true,
  //   "icon": "logos:vitejs",
  //   "tab": true,
  //   "component": "/demo/documents/vite/index.vue",
  //   "pid": 32,
  //   "id": 34
  // },
  // {
  //   "name": "documentsVueuse",
  //   "path": "/demo/documents/vueuse",
  //   "title": "VueUse (external link)",
  //   "require": true,
  //   "icon": "logos:vueuse",
  //   "tab": true,
  //   "href": "https://vueuse.org/guide/",
  //   "component": "null",
  //   "pid": 32,
  //   "id": 35
  // },
  // {
  //   "name": "error",
  //   "path": "/demo/error",
  //   "title": "Exception page",
  //   "require": true,
  //   "icon": "icon-park-outline:error-computer",
  //   "tab": true,
  //   "type": "dir",
  //   "component": null,
  //   "pid": 13,
  //   "id": 36
  // },
  // {
  //   "name": "demo403",
  //   "path": "/demo/error/403",
  //   "title": "403",
  //   "require": true,
  //   "icon": "carbon:error",
  //   "tab": true,
  //   "sort": 3,
  //   "component": "/error/403/index.vue",
  //   "pid": 36,
  //   "id": 37
  // },
  // {
  //   "name": "demo404",
  //   "path": "/demo/error/404",
  //   "title": "404",
  //   "require": true,
  //   "icon": "icon-park-outline:error",
  //   "tab": true,
  //   "sort": 2,
  //   "component": "/error/404/index.vue",
  //   "pid": 36,
  //   "id": 38
  // },
  // {
  //   "name": "demo500",
  //   "path": "/demo/error/500",
  //   "title": "500",
  //   "require": true,
  //   "icon": "carbon:data-error",
  //   "tab": true,
  //   "sort": 1,
  //   "component": "/error/500/index.vue",
  //   "pid": 36,
  //   "id": 39
  // },
  // {
  //   "name": "about",
  //   "path": "/about",
  //   "title": "About",
  //   "require": true,
  //   "icon": "icon-park-outline:info",
  //   "tab": true,
  //   "component": "/demo/about/index.vue",
  //   "pid": null,
  //   "id": 40
  // },
  // {
  //   "name": "cascader",
  //   "path": "/demo/cascader",
  //   "title": "Provincial and municipal linkage",
  //   "require": true,
  //   "icon": "icon-park-outline:add-subset",
  //   "tab": true,
  //   "component": "/demo/cascader/index.vue",
  //   "pid": 13,
  //   "id": 41
  // },
  // {
  //   "name": "documentsNova",
  //   "path": "/documents/nova",
  //   "title": "Nova docs",
  //   "require": true,
  //   "icon": "local:logo",
  //   "tab": true,
  //   "href": "https://nova-admin-docs.netlify.app/",
  //   "component": "2333333",
  //   "pid": 32,
  //   "id": 42
  // },
  // {
  //   "name": "dict",
  //   "path": "/demo/dict",
  //   "title": "Dictionary Example",
  //   "require": true,
  //   "icon": "icon-park-outline:book-one",
  //   "tab": true,
  //   "component": "/demo/dict/index.vue",
  //   "pid": 13,
  //   "id": 43
  // },
  // {
  //   "name": "task",
  //   "path": "/demo/task",
  //   "title": "Task Example",
  //   "require": true,
  //   "icon": "icon-park-outline:six-circular-connection",
  //   "tab": true,
  //   "component": "/demo/tasks/index.vue",
  //   "pid": 13,
  //   "id": 44
  // },
  // {
  //   "name": "dataOffline",
  //   "path": "/demo/data-offline",
  //   "title": "Data Offline",
  //   "require": true,
  //   "icon": "icon-park-outline:data-switching",
  //   "tab": true,
  //   "component": "/demo/offline-sync/index.vue",
  //   "pid": 13,
  //   "id": 59
  // },
  // {
  //   "name": "menu-demo",
  //   "path": "/demo/menu-demo",
  //   "title": "Menu Demo",
  //   "require": true,
  //   "icon": "icon-park-outline:data-switching",
  //   "tab": true,
  //   "component": "/demo/menu-demo/index.vue",
  //   "pid": 13,
  //   "id": 62
  // }
]
