import type { Menu } from './types'

export const demoMenus: Menu[] = [
  {
    id: 'm_root_1',
    title: 'Home',
    icon: 'ri-home-4-line',
    pid: null,
    type: 'CONTENT',
    refId: 'content_home',
    url: null,
    sort: 10,
    flag: 1,
    created: { by: 'system', at: new Date().toISOString() },
  },
  {
    id: 'm_root_2',
    title: 'Products',
    icon: 'ri-store-2-line',
    pid: null,
    type: 'CATEGORY',
    refId: 'cat_products',
    url: null,
    sort: 20,
    flag: 1,
    created: { by: 'admin', at: '2025-01-05T10:00:00.000Z' },
  },
  {
    id: 'm_item_2_1',
    title: 'Electronics',
    icon: 'ri-briefcase-4-line',
    pid: 'm_root_2',
    type: 'CATEGORY',
    refId: 'cat_electronics',
    url: null,
    sort: 10,
    flag: 1,
    created: { by: 'admin', at: '2025-01-05T10:10:00.000Z' },
  },
  {
    id: 'm_item_2_2',
    title: 'Clothing',
    icon: 'ri-shirt-line',
    pid: 'm_root_2',
    type: 'CATEGORY',
    refId: 'cat_clothing',
    url: null,
    sort: 20,
    flag: 1,
    created: { by: 'admin', at: '2025-01-06T08:30:00.000Z' },
  },
  {
    id: 'm_root_3',
    title: 'Blog',
    icon: 'ri-book-2-line',
    pid: null,
    type: 'CONTENT',
    refId: 'content_blog',
    url: null,
    sort: 30,
    flag: 1,
    created: { by: 'editor', at: '2025-02-01T09:00:00.000Z' },
  },
  {
    id: 'm_external_1',
    title: 'External Docs',
    icon: 'ri-link',
    pid: null,
    type: 'EXTERNAL',
    refId: null,
    url: 'https://example.com/docs',
    sort: 40,
    flag: 0,
    created: { by: 'system', at: new Date().toISOString() },
  },
  {
    id: 'm_tool_group',
    title: 'Tools',
    icon: 'ri-hammer-line',
    pid: null,
    type: 'GROUP',
    refId: null,
    url: null,
    sort: 50,
    flag: 1,
    created: { by: 'admin', at: '2025-03-10T12:00:00.000Z' },
  },
  {
    id: 'm_tool_child',
    title: 'API Tester',
    icon: 'ri-terminal-box-line',
    pid: 'm_tool_group',
    type: 'CONTENT',
    refId: 'content_api_tester',
    url: null,
    sort: 10,
    flag: 1,
    created: { by: 'dev', at: '2025-03-11T09:15:00.000Z' },
  },
]

export const demoRefItems = [
  // CATEGORY
  { id: '68ff7d49fcff9e2aa0aedd71', type: 'CATEGORY', title: 'Tin tức nổi bật' },
  { id: '68ff7d8bfcff9e2aa0aedd77', type: 'CATEGORY', title: 'Phong cách thiết kế' },
  { id: '68ff7dfffcff9e2aa0aedd83', type: 'CATEGORY', title: 'Mẫu sản phẩm đẹp' },

  // NEWS CONTENT
  { id: '6900624f51b8164adff968c7', type: 'CONTENT', title: 'Phong thủy phòng ngủ và những điều cấm kỵ' },
  { id: '690062a651b8164adff968cd', type: 'CONTENT', title: 'Nhà hướng Nam và những điều cần biết' },

  // PRODUCT CONTENT
  { id: '690076c0c9e0567ce98bc52e', type: 'CONTENT', title: 'Thiết kế kiến trúc biệt thự' },
  { id: '69007892c9e0567ce98bc548', type: 'CONTENT', title: 'Thiết kế kiến trúc biệt thự 2' }
]